### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Xentinel2** [HengfengLi/Spelling-Correction#2]
I have just one word in words.txt and I want to print the distance of the Editex method so I write in the console a word and then I got this.

![error](https://cloud.githubusercontent.com/assets/20759608/24467309/3d61681c-1471-11e7-8784-a37a60485dd2.PNG)

**Comment by hengfengli** [comment]
I guess this is because it includes non-alpha characters, so that's why lettersInfo[char1-'a'] fails in Editex.isSameGroup() function. I just modified the code, please check it again.
